// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt7ceqNdFKIs8c6WdnAoJlwxks0KumJ9Y',
    appId: '1:79626302877:web:593b992c235f1165eaab74',
    messagingSenderId: '79626302877',
    projectId: 'capstone-bf0b4',
    authDomain: 'capstone-bf0b4.firebaseapp.com',
    storageBucket: 'capstone-bf0b4.appspot.com',
    measurementId: 'G-361R7KN2X2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeM85Of3FmxLCdUOMjj87MeJVtcmTaEYE',
    appId: '1:79626302877:android:c46e0638b8ed2db5eaab74',
    messagingSenderId: '79626302877',
    projectId: 'capstone-bf0b4',
    storageBucket: 'capstone-bf0b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw6ojto941ftIFl2-SQmhxmZVZaVY6UZw',
    appId: '1:79626302877:ios:6cabf6062a477549eaab74',
    messagingSenderId: '79626302877',
    projectId: 'capstone-bf0b4',
    storageBucket: 'capstone-bf0b4.appspot.com',
    iosClientId: '79626302877-8sd86t857ignrclng060vh0jvih6hdds.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
