// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJODBUVuDQPu5LyclMxLfcGY4Os3_FKd4',
    appId: '1:11142186328:web:fcd65085994c67bbe7112d',
    messagingSenderId: '11142186328',
    projectId: 'capstone-37874',
    authDomain: 'capstone-37874.firebaseapp.com',
    storageBucket: 'capstone-37874.appspot.com',
    measurementId: 'G-34EFLZJ8DG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXLdTr34AKqhXT2OLXdwhT2KvQ0qm5Jao',
    appId: '1:11142186328:android:3cda7761245d0dade7112d',
    messagingSenderId: '11142186328',
    projectId: 'capstone-37874',
    storageBucket: 'capstone-37874.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8vWdEDD0wqNvFwuDpE-zpO_IqmXOLFqk',
    appId: '1:11142186328:ios:2a3fa1efd6244e6fe7112d',
    messagingSenderId: '11142186328',
    projectId: 'capstone-37874',
    storageBucket: 'capstone-37874.appspot.com',
    iosClientId: '11142186328-2nkuih5tt4e67ekf5eual6h8fkm6shjv.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8vWdEDD0wqNvFwuDpE-zpO_IqmXOLFqk',
    appId: '1:11142186328:ios:2a3fa1efd6244e6fe7112d',
    messagingSenderId: '11142186328',
    projectId: 'capstone-37874',
    storageBucket: 'capstone-37874.appspot.com',
    iosClientId: '11142186328-2nkuih5tt4e67ekf5eual6h8fkm6shjv.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
